### ISSUE TITLE
CET Timezone not honored

### ISSUE THREAD

**Issue by ca1f** [araddon/dateparse#113]
It seems that the CET timezone is not properly detected.

Adding the values `Thu, 17 Dec 2020 15:39:13 GMT` and `Thu, 17 Dec 2020 16:39:13 CET` to the example and verifying that these values are pointing to the same time with

```go
t0, _ := time.Parse(time.RFC1123, "Thu, 17 Dec 2020 15:39:13 GMT")
t1, _ := time.Parse(time.RFC1123, "Thu, 17 Dec 2020 16:39:13 CET")
fmt.Println(t0.Equal(t1))
```

Parsing these values with `dateparse.ParseAny` yields the following results:
```
| Thu, 17 Dec 2020 15:39:13 GMT                         | 2020-12-17 15:39:13 +0000 UTC           |
| Thu, 17 Dec 2020 16:39:13 CET                         | 2020-12-17 16:39:13 +0000 UTC           |
```

These are not the same.

Expected results:
```
| Thu, 17 Dec 2020 15:39:13 GMT                         | 2020-12-17 15:39:13 +0000 UTC           |
| Thu, 17 Dec 2020 16:39:13 CET                         | 2020-12-17 16:39:13 +1000 CET           |
```

**Comment by araddon** [comment]
Thank you for the report!   

I did end up pushing a fix for this, however the end result Is still not possibly same as you seek.  I was not able to repro results above without overriding time.Local  https://play.golang.org/p/EK_VQP5SjTD
