### ISSUE TITLE
Relative dates/times

### ISSUE THREAD

**Issue by rendaw** [araddon/dateparse#115]
Sometimes dates like "today", "now", "yesterday", "3 days ago" come up in data sets and it would be useful to be able to parse these.  Maybe a reference date could be set, similar to locale for local parsing?

**Comment by gouguoyin** [comment]
you can try [go-carbon](https://github.com/golang-module/carbon)

**Comment by araddon** [comment]
same/similar https://github.com/araddon/dateparse/issues/12

**Comment by rendaw** [comment]
Oh yep, sorry! I searched but must have missed that.
