### ISSUE TITLE
Parsing ISO 8601 datetime without seconds

### ISSUE THREAD

**Issue by eggfriedrice** [araddon/dateparse#14]
Hey, thanks for this library, it looks great!

Just one problem I've spotted so far, it works fine with an ISO 8601 like this `2009-08-12T22:15:09Z` (from your examples)

But removing the seconds field to make it `2009-08-12T22:15Z` gives this error: 
> parsing time "2009-08-12T22:15Z" as "2006-01-02T15:04:05Z": cannot parse "Z" as ":"

I believe this is a valid string per the 8601 spec (but don't quote me!), is this a bug?

**Comment by araddon** [comment]
Thanks for the report, i have a pr up, let me run it by @junichif and get it in today.

**Comment by araddon** [comment]
Here is test/example:  https://github.com/araddon/dateparse/blob/master/parseany_test.go#L272

**Comment by eggfriedrice** [comment]
Awesome! :+1:
