### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by matiux** [araddon/dateparse#17]
Hi, I'm getting this error:

```
panic: parsing time "Thu, 13 Jul 2017 08:58:40 +0100" as "Mon, 02 Jan 2006 15:04:05 MST": cannot parse "+0100" as "MST"
```

with this string `Thu, 13 Jul 2017 08:58:40 +0100`

How can I solve?

**Comment by araddon** [comment]
writing a test now, possibly a new it hadn't seen before.
