### ISSUE TITLE
Local time

### ISSUE THREAD

**Issue by matiux** [araddon/dateparse#20]
Is there a way to convert a string like this `Thu, 13 Jul 2017 08:16:43 -0700` in my local time ?

After parsing I obtain an time.Time object `2017-07-13 08:16:43 -0700 -0700` but seem to be 9 hours back

**Comment by araddon** [comment]
Yes, i have actually been mulling how to best support this.   Let me Push something up to support it.

>>> When parsing a time with a zone abbreviation like MST, if the zone abbreviation has a defined offset in the current location, then that offset is used. The zone abbreviation "UTC" is recognized as UTC regardless of location. If the zone abbreviation is unknown, Parse records the time as being in a fabricated location with the given zone abbreviation and a zero offset. This choice means that such a time can be parsed and reformatted with the same layout losslessly, but the exact instant used in the representation will differ by the actual zone offset. To avoid such problems, prefer time layouts that use a numeric zone offset, or use ParseInLocation.   From https://golang.org/pkg/time/#Parse

**Comment by matiux** [comment]
Thanks, I'll waiting :)

**Comment by araddon** [comment]
Before i do anything, can you try setting  `time.Local` https://golang.org/src/time/zoneinfo.go?#L65 to a valid `Location` from LoadLocation?  https://golang.org/pkg/time/#LoadLocation

**Comment by araddon** [comment]
An example:   https://play.golang.org/p/IDHRalIyXh

**Comment by matiux** [comment]
This is the output of you code:

```
t  2006-01-02 15:04:05 +0000 UTC  zone:MST  offset:0 
t  2006-01-02 15:04:05 +0000 UTC  zone:UTC  offset:0 
l America/Denver
t  2006-01-02 22:04:05 +0000 UTC  zone:MST  offset:-25200 
t  2006-01-02 15:04:05 +0000 UTC  zone:UTC  offset:0
```

**Comment by matiux** [comment]
it's enough?

**Comment by araddon** [comment]
I believe the desired behavior you seek can be achieved if you just set the global time.Local to your desired zone?

**Comment by araddon** [comment]
ok, have a pr with few new apis exposed.  

https://github.com/araddon/dateparse/pull/26

**Comment by cynipe** [comment]
nice!!
Looks good to me!!
