### ISSUE TITLE
Parse: 2017-12-11 10:16 (with no seconds)

### ISSUE THREAD

**Issue by mmcquillan** [araddon/dateparse#31]
Does not seem to parse no seconds with the date format having dashes and not slashes.

AND... fantastic library, thank you!

**Comment by araddon** [comment]
Thanks for the report, glad its useful!

**Comment by mmcquillan** [comment]
Very useful and using it in my AWS Logs cli: https://github.com/mmcquillan/lawsg

Thanks again!
