### ISSUE TITLE
Request: ParseFormat

### ISSUE THREAD

**Issue by Redundancy** [araddon/dateparse#33]
It would be nice to have a version that outputs a date format string for Go, so that once a format is known it could be used on subsequent parsing more efficiently.

**Comment by araddon** [comment]
I like that idea. Would require some refactoring but let me try it.   I am a little concerned that non-zero filled dates such as `1-1-2017` are ambiguous (when the date value passed in is `10-10-2017` and it would not be readily apparent in all circumstances.

**Comment by Redundancy** [comment]
I was also wondering if a version that can resolve ambiguity with a corpus of samples might be possible? :)

**Comment by araddon** [comment]
@Redundancy i have thought about a training function.  The problem i have encountered trying to do this approach is:   Ensuring all possibilities of variation exist (for instance, training on 100k records, but only over a 1 or 2 day period so you can't disambiguate the mm/dd vs dd/mm issue.

**Comment by araddon** [comment]
notes for possible implementation:

All of the public methods `ParseAny` etc returns a `(time.Time, error)` in this call to private func https://github.com/araddon/dateparse/blob/1d15b8a8bb580bd040a769ce7cf75dfdf4c42d01/parseany.go#L296-L298

The `parser` created on Line 298 calls `parser.parse()` , the `parse` method needs to be modified to return `(string, error)` OR `(parser, error)` where the string is the format.   Then, a different public method can return that string, and current ones can parse using that string format.  https://github.com/araddon/dateparse/blob/1d15b8a8bb580bd040a769ce7cf75dfdf4c42d01/parseany.go#L1266-L1269

**Comment by araddon** [comment]
closed in #52
