### ISSUE TITLE
Request: Support for dot-format (e.g. 01.01.2014)

### ISSUE THREAD

**Issue by ffischer1984** [araddon/dateparse#34]
It would be nice to support dotted-formats like  12.12.2014

**Comment by araddon** [comment]
ok, no problem, can you post a few examples?   And would it be date only or do they ever have time?

**Comment by ffischer1984** [comment]
date only. here are some examples
24.12.2014 13:30
24.12.14 // a little odd but:
23.12.84 // very common in old data means 23.12.1984
 
thanks for the commit

**Comment by araddon** [comment]
Don't think my commit will work, those are dd.mm.yyyy while i did mm.dd.yyyy.   I have another ticket that is open that talks about needing a different method for choosing between dd.mm.yyyy vs mm.dd.yyyy when it is ambiguous.
