### ISSUE TITLE
Could not find time offset

### ISSUE THREAD

**Issue by johndark** [araddon/dateparse#40]
Hi,

if we will do something like:
`a := time.Now().Local().Add(time.Hour*time.Duration(0) +`
`     time.Minute*time.Duration(30) +`
`     time.Second*time.Duration(0))`

(it's just offset for 30 mins from now), we will get:
`2018-02-11 15:55:38.194708 +0300 MSK`

in `a` variable, for example. Let's place this value like a string type:
`a := "2018-02-11 15:55:38.194708 +0300 MSK"`

and try to use ParseLocal() for this string variable:
`t, _ := dateparse.ParseLocal(a)`

we will get `0001-01-01 00:00:00 +0000 UTC`.

**Comment by araddon** [comment]
What is time.Local set to?    if you do log output of the global variable that will help me look at it.

**Comment by johndark** [comment]
time.Local is UTC

We can use your main example and set

    var examples = []string{
        "2018-02-11 15:55:38.194708 +0300 MSK",
    }

    var (
        timezone = "Etc/UTC"
    )

Run program and we will get something like:

    panic: Could not find date format for 2018-02-11 15:55:38.194708 +0300 MSK
    goroutine 1 [running]:
    main.main()
	    main.go:117 +0x50e

Maybe I missed something?

**Comment by araddon** [comment]
investigating, tried a few easy edits and didn't get it so will poke at it some more.

**Comment by araddon** [comment]
```
dateparse/dateparse$ ./dateparse --timezone="Europe/Moscow" "2018-02-11 15:55:38 +0300 MSK"

Your Current time.Local zone is PST

+------------+---------------------------+-------------------------------+-------------------------------+
| method     | Zone Source               | Parsed                        | Parsed: t.In(time.UTC)        |
+------------+---------------------------+-------------------------------+-------------------------------+
| ParseAny   | time.Local = nil          | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseAny   | time.Local = timezone arg | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseAny   | time.Local = time.UTC     | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseIn    | time.Local = nil          | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseIn    | time.Local = timezone arg | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseIn    | time.Local = time.UTC     | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseLocal | time.Local = nil          | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseLocal | time.Local = timezone arg | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
| ParseLocal | time.Local = time.UTC     | 2018-02-11 15:55:38 +0300 MSK | 2018-02-11 12:55:38 +0000 UTC |
+------------+---------------------------+-------------------------------+-------------------------------+

```

**Comment by araddon** [comment]
Thank you for the report!

**Comment by johndark** [comment]
Thanks for your dateparse and fix :)
