### ISSUE TITLE
What happens with multiple dates within a string?

### ISSUE THREAD

**Issue by MedLexAI** [araddon/dateparse#51]
This isn't an issue, but more of an implementation question. Apologies in advance if this is not the right place for a question.

I have text pages with multiple dates on each page, sometimes with different dates on the same line.

I was thinking about passing dateparse each line in a file, but from the examples it looks like it only works with single strings. So what is the behavior of dateparse when multiple dates are included within a string?

I am assuming I need to figure out some method of tokenization of each line in these text files in order to hand dateparse only a single date candidate to convert?

Thanks in advance

**Comment by araddon** [comment]
Do you have any examples?   It would seem reasonable to do the tokenization within using a `Next()` type interface.   But, not 100% sure.

**Comment by araddon** [comment]
Hm, that would likely require pre-processing to extract the tokens.

**Comment by MedLexAI** [comment]
So probably a stack of regex to pull common date formats, then pass them to dateparse?

**Comment by araddon** [comment]
Closing this as beyond scope of this tool.
