### ISSUE TITLE
Small extension on a format

### ISSUE THREAD

**Issue by ferhatelmas** [araddon/dateparse#62]
Regarding fix in #61, how about `sept. 28, 2017` ?

```go
dateparse.ParseAny(sept. 28, 2017)
> cannot parse "sept. 28, 2017" as "Jant. "
```

**Comment by ferhatelmas** [comment]
@araddon do you think if this will be fixed at some point or is it a `won't fix` issue ?

**Comment by araddon** [comment]
Whoops, sorry, i missed this one somehow.  looking at it now...
