### ISSUE TITLE
DD-Mon-YYYY

### ISSUE THREAD

**Issue by carbocation** [araddon/dateparse#69]
Currently seeing the following:

```
2018/10/09 12:04:23 parsing time "29-Jun-2016 18:09:59" as "29-Jan-2016 18:09:59": cannot parse "-Jun-2016 18:09:59" as "9-"
```

Is there any way for us to pass in our own string formats so when we detect a bad one like this (that has an easy interpretation) we can ensure it gets parsed correctly?

**Comment by araddon** [comment]
That is a new format, will create a state to recognize it.  Unfortunately adding new formats is not that easy in this library, because there are tens of thousands of permutations possible, this creates the format-string dynamically not a try/fail based approach (which is much slower).
