### ISSUE TITLE
Cannot parse string with 1 day digit and June/July

### ISSUE THREAD

**Issue by LutherLu1** [araddon/dateparse#70]
### Observed Behavior
```
$./dateparse "1 July 2013" 
fatal: parsing time "1 July 2013" as "2 Jany 2006": cannot parse "uly 2013" as " Jany "
```

### Expected Behavior
Parses string without error

### Notes
I also observe this behavior on the latest commit with "9 June 2013" but not with "19 June 2013"

**Comment by araddon** [comment]
thanks for the report, will get this as soon im back from travelling, probably be a few days.

**Comment by araddon** [comment]
sorry it took so long, fix merged in, thank you for report.
