### ISSUE TITLE
Another date format: 'January 02, 2006, 15:04:05'

### ISSUE THREAD

**Issue by timsims1717** [araddon/dateparse#73]
I've just run into a few more date formats that I think would be good to have:
January 02, 2006, 15:04:05
January 02, 2006 15:04:05
January 02, 2006 03:04:05 pm
Basically, the same as "September 17, 2012 at 10:09am PST-08" but without the 'at' and a couple variations.

Thanks!

**Comment by timsims1717** [comment]
I just noticed the very first one on the list fits, but having 24 hour as an option would be nice.

**Comment by araddon** [comment]
thanks for the report, will try to get them in next couple days!
