### ISSUE TITLE
Should suffixes be allowed?

### ISSUE THREAD

**Issue by eslindsey** [araddon/dateparse#74]
I have a date formatted as `November 7th, 2018` and the parsing fails at the `7th` part. Should suffixes be allowed?

**Comment by araddon** [comment]
Well, go lib doesn't like it much, let me play with it and see how possible it is.  https://play.golang.org/p/DD9TAXaKWWl

**Comment by eslindsey** [comment]
Yes, I already know that Go doesn't like them.

I tried a couple of different options to work around this issue. I'm curious to know if there are any other more creative ways to solve the problem.

First, I benchmarked the original code:

    $ go test -bench Parse
    goos: linux
    goarch: amd64
    pkg: github.com/eslindsey/dateparse
    BenchmarkShotgunParse-4            20000             85675 ns/op           13136 B/op        169 allocs/op
    BenchmarkParseAny-4                50000             29390 ns/op            4336 B/op         45 allocs/op
    BenchmarkParseDateString-4         30000             35384 ns/op             208 B/op         13 allocs/op
    PASS
    ok      github.com/eslindsey/dateparse  7.105s

# Regular Expressions

Then, I compiled a regular expression in init and used it to replace all instances of the suffixes with the ordinals:

    var NumberSuffixes = regexp.MustCompile(`(\d)(st|nd|rd|th)\b`)
    ...
    datestr = re.ReplaceAllString(datestr, "$1")

Performance was not satisfactory. It ran 5x slower and nearly doubled the number of allocations:

    $ go test -bench Parse
    goos: linux
    goarch: amd64
    pkg: github.com/eslindsey/dateparse
    BenchmarkShotgunParse-4            20000             85854 ns/op           13136 B/op        169 allocs/op
    BenchmarkParseAny-4                10000            145080 ns/op            5360 B/op         87 allocs/op
    BenchmarkParseDateString-4         50000             56193 ns/op             208 B/op         13 allocs/op
    PASS
    ok      github.com/eslindsey/dateparse  8.593s

Then I tried converting the string to a byte slice in case the call to `ReplaceAllString` could be optimized more as a call to `ReplaceAll`:

    datestr = string(NumberSuffixes.ReplaceAll([]byte(datestr), []byte{'$','1'}))

Apparently not:

    $ go test -bench Parse
    goos: linux
    goarch: amd64
    pkg: github.com/eslindsey/dateparse
    BenchmarkShotgunParse-4            20000             85723 ns/op           13136 B/op        169 allocs/op
    BenchmarkParseAny-4                10000            147180 ns/op            5760 B/op        101 allocs/op
    BenchmarkParseDateString-4         50000             47357 ns/op             208 B/op         13 allocs/op
    PASS
    ok      github.com/eslindsey/dateparse  8.019s

# String Manipulation

I tried simple string replacement:

        // Eliminate suffixes from numbers before processing
        datestr = strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(
                  strings.Replace(datestr,
                  "1st", "1", -1),
                  "2nd", "2", -1),
                  "3rd", "3", -1),
                  "4th", "4", -1),
                  "5th", "5", -1),
                  "6th", "6", -1),
                  "7th", "7", -1),
                  "8th", "8", -1),
                  "9th", "9", -1),
                  "0th", "0", -1),
                  "1th", "1", -1), // 11th
                  "2th", "2", -1), // 12th
                  "3th", "3", -1)  // 13th

It's ugly, but I was surprised at how efficient this one was, only 33% slower than the original, and no extra allocations if the string isn't found. I would have expected the compiled state machine from the previous test to be more efficient, but I guess not:

    $ go test -bench Parse
    goos: linux
    goarch: amd64
    pkg: github.com/eslindsey/dateparse
    BenchmarkShotgunParse-4            20000             86042 ns/op           13136 B/op        169 allocs/op
    BenchmarkParseAny-4                30000             40620 ns/op            4336 B/op         45 allocs/op
    BenchmarkParseDateString-4         50000             50755 ns/op             208 B/op         13 allocs/op
    PASS
    ok      github.com/eslindsey/dateparse  8.339s

When I add in some suffixes so that replacement must occur, I obtain the following results (of course we are no longer comparing apples to apples here):

    $ go test -bench Parse
    goos: linux
    goarch: amd64
    pkg: github.com/eslindsey/dateparse
    BenchmarkShotgunParse-4            20000             78854 ns/op           13584 B/op        171 allocs/op
    BenchmarkParseAny-4                30000             45551 ns/op            4944 B/op         65 allocs/op
    BenchmarkParseDateString-4         30000             43081 ns/op             208 B/op         13 allocs/op
    PASS
    ok      github.com/eslindsey/dateparse  7.208s

So using string manipulation, we could incur a slight (33%) performance penalty if the string doesn't contain suffixes, and a 55% speed penalty if replacement must occur.

If there is a more efficient approach, I'm all ears. If not, then I will leave it up to you whether you want that 33% performance hit in exchange for more flexibility with date formats.

**Comment by araddon** [comment]
Let me know if those changes worked if you can, thank you!

**Comment by eslindsey** [comment]
This fix appears to have solved the problem.

I didn't realize the complexity of the parser at first glance; I should have inspected the source code more fully. This will be much more efficient than the approach I was taking.

**Comment by eslindsey** [comment]
Without understanding the entire parser, will this handle all of the scenarios listed in https://github.com/araddon/dateparse/issues/74#issuecomment-441119351?

Specifically:

    \d*1st
    \d*2nd
    \d*3rd
    \d*[04-9]th
    \d*11th
    \d*12th
    \d*13th

I believe that covers all of the suffixes.
